// Package models contains the types for schema ''.
package models

// Code generated by xo. DO NOT EDIT.

// Relation represents a row from 'relation'.
type Relation struct {
	KizamiID int `json:"kizami_id"` // kizami_id
}
